FROM nginx:alpine

COPY index.html style.css app.js pkbld.html loginstyle.css /usr/share/nginx/html/
COPY images/ /usr/share/nginx/html/images/
COPY ./*.html ./*.css ./*.js ./**/*.jpg ./**/*.png /usr/share/nginx/html/